server:
  port: 9991

spring:
  application:
    name: service-hello
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}  #实例ID
        health-check-path: /actuator/health                                                       #健康检查
        health-check-interval: 10s
        prefer-ip-address: true